[package]
name = "rust-4chan"
version = "0.1.0"
authors = ["Salvador Guzman <guzmansalv@gmail.com>"]

[dependencies]
reqwest = "0.8.6"
serde = "1.0.69"
serde_json = "1.0.22"
serde_derive = "1.0.69"
chrono = "0.4.4"